BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "helios9"
BBFILE_PATTERN_helios9 = "^${LAYERDIR}/"
BBFILE_PRIORITY_helios9 = "10"
LAYERSERIES_COMPAT_helios9 = "scarthgap"

LAYERVERSION_helios9 = "1"

LAYERDEPENDS_helios9 = "core"
