FROM debian:bullseye-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update
RUN apt-get install -y build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-subunit python3-websockets socat texinfo unzip wget xz-utils zstd tmux
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
RUN locale-gen

ARG USER_NAME=kas
ARG USER_ID=${USER_ID}

RUN useradd -u ${USER_ID} -m -s /bin/bash ${USER_NAME}

USER $USER_NAME
WORKDIR /home/${USER_NAME}

ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US:en"
ENV LC_ALL="en_US.UTF-8"
ENV PATH="/home/${USER_NAME}/.local/bin:${PATH}"
ENV QB_SLIRP_OPT="-nic user,model=virtio-net-pci"

RUN uv python install 3.13 --install-dir /home/${USER_NAME}/.local/bin
RUN uv venv .venv
RUN uv pip install kas
RUN echo ". /home/${USER_NAME}/.venv/bin/activate" >> /home/${USER_NAME}/.bashrc

WORKDIR /home/${USER_NAME}/yocto

CMD [ "bash" ]
