# helios9 distribution configuration

DISTRO = "helios9-distro"
DISTRO_NAME = "helios9-distro"
DISTRO_VERSION = "0.1"
DISTRO_CODENAME = "scarthgap"

# SDK naming
SDK_VENDOR = "-helios9_distro_sdk"
SDK_VERSION = "${DISTRO_VERSION}"
SDK_NAME = "${DISTRO}-${TCLIBC}-${SDKMACHINE}-${IMAGE_BASENAME}-${TUNE_PKGARCH}-${MACHINE}"

# Use systemd
DISTRO_FEATURES = "acl ext2 ipv4 usbhost xattr systemd systemd-resolved usrmerge vfat"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
INIT_MANAGER = "systemd"

# Use IPK packages (fastest)
PACKAGE_CLASSES = "package_ipk"

# Version information
DISTRO_EXTRA_RDEPENDS:append = " os-release"

# Disable syslog
VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""

SYMLINK_RESOLV_CONF = "1"

CMDLINE:append = " systemd.repart=yes"

ROOT_PART_TYPE = "${@bb.utils.contains('TUNE_FEATURES', 'aarch64', '8305', '8304', d)}"
WICVARS:append = " ROOT_PART_TYPE"
